/**
 * 2017 HKDSE Category A written-paper sessions.
 * Source of truth: official Annex 1 Examination Timetable (日期及時間 / 應考科目).
 * Clock times are not printed on Annex 1 (AM/PM only). Encoded assumptions:
 *   AM  = 08:30:00 HKT (Asia/Hong_Kong, UTC+8)
 *   PM  = 13:30:00 HKT
 *   Paper 3 listening = AM 08:30 unless Annex 1 places the paper in PM.
 * All instants are absolute ISO-8601 timestamps with +08:00.
 */
window.HKDSE_2017 = {
  year: 2017,
  timezone: "Asia/Hong_Kong",
  timezoneLabel: "香港時間 (HKT, UTC+8)",
  source: {
    zh: "2017 年香港中學文憑考試時間表（附件一）",
    en: "Examination Timetable for 2017 HKDSE (Annex 1)",
  },
  assumptions: {
    am: "08:30:00",
    pm: "13:30:00",
  },
  sessions: [
    {
      id: "va-p1",
      subjectZh: "視覺藝術",
      subjectEn: "Visual Arts",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-03-31T08:30:00+08:00",
      period: "AM",
      category: "arts",
    },
    {
      id: "va-p2",
      subjectZh: "視覺藝術",
      subjectEn: "Visual Arts",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-03-31T13:30:00+08:00",
      period: "PM",
      category: "arts",
    },
    {
      id: "is-p1",
      subjectZh: "綜合科學",
      subjectEn: "Integrated Science",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-01T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "is-p2",
      subjectZh: "綜合科學",
      subjectEn: "Integrated Science",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-01T13:30:00+08:00",
      period: "PM",
      category: "science",
    },
    {
      id: "phy-p1",
      subjectZh: "物理",
      subjectEn: "Physics",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-01T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "phy-p2",
      subjectZh: "物理",
      subjectEn: "Physics",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-01T13:30:00+08:00",
      period: "PM",
      category: "science",
    },
    {
      id: "csp",
      subjectZh: "組合科學（物理）",
      subjectEn: "Combined Science (Physics)",
      paperZh: "筆試",
      paperEn: "Written paper",
      start: "2017-04-01T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "ls-p1",
      subjectZh: "通識教育",
      subjectEn: "Liberal Studies",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-03T08:30:00+08:00",
      period: "AM",
      category: "core",
    },
    {
      id: "ls-p2",
      subjectZh: "通識教育",
      subjectEn: "Liberal Studies",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-03T13:30:00+08:00",
      period: "PM",
      category: "core",
    },
    {
      id: "chi-p1",
      subjectZh: "中國語文",
      subjectEn: "Chinese Language",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-05T08:30:00+08:00",
      period: "AM",
      category: "core",
    },
    {
      id: "chi-p2",
      subjectZh: "中國語文",
      subjectEn: "Chinese Language",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-05T13:30:00+08:00",
      period: "PM",
      category: "core",
    },
    {
      id: "chi-p3",
      subjectZh: "中國語文",
      subjectEn: "Chinese Language",
      paperZh: "卷三（聆聽及綜合能力考核）",
      paperEn: "Paper 3 (Listening and Integrated Skills)",
      start: "2017-04-06T08:30:00+08:00",
      period: "AM",
      category: "core",
      note: "listening",
    },
    {
      id: "eng-p1",
      subjectZh: "英國語文",
      subjectEn: "English Language",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-07T08:30:00+08:00",
      period: "AM",
      category: "core",
    },
    {
      id: "eng-p2",
      subjectZh: "英國語文",
      subjectEn: "English Language",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-07T13:30:00+08:00",
      period: "PM",
      category: "core",
    },
    {
      id: "eng-p3",
      subjectZh: "英國語文",
      subjectEn: "English Language",
      paperZh: "卷三（聆聽及綜合能力考核）",
      paperEn: "Paper 3 (Listening and Integrated Skills)",
      start: "2017-04-08T08:30:00+08:00",
      period: "AM",
      category: "core",
      note: "listening",
    },
    {
      id: "math-p1",
      subjectZh: "數學必修部分",
      subjectEn: "Mathematics Compulsory Part",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-10T08:30:00+08:00",
      period: "AM",
      category: "core",
    },
    {
      id: "math-p2",
      subjectZh: "數學必修部分",
      subjectEn: "Mathematics Compulsory Part",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-10T13:30:00+08:00",
      period: "PM",
      category: "core",
    },
    {
      id: "tl-p1",
      subjectZh: "科技與生活",
      subjectEn: "Technology and Living",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-11T08:30:00+08:00",
      period: "AM",
      category: "applied",
    },
    {
      id: "tl-p2",
      subjectZh: "科技與生活",
      subjectEn: "Technology and Living",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-11T13:30:00+08:00",
      period: "PM",
      category: "applied",
    },
    {
      id: "chem-p1",
      subjectZh: "化學",
      subjectEn: "Chemistry",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-12T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "chem-p2",
      subjectZh: "化學",
      subjectEn: "Chemistry",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-12T13:30:00+08:00",
      period: "PM",
      category: "science",
    },
    {
      id: "csc",
      subjectZh: "組合科學（化學）",
      subjectEn: "Combined Science (Chemistry)",
      paperZh: "筆試",
      paperEn: "Written paper",
      start: "2017-04-12T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "liteng-p1",
      subjectZh: "英語文學",
      subjectEn: "Literature in English",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-13T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "dat-0413",
      subjectZh: "設計與應用科技",
      subjectEn: "Design and Applied Technology",
      paperZh: "卷一及卷二（註 2 檔期）",
      paperEn: "Papers 1 & 2 (Note 2 slot)",
      start: "2017-04-13T08:30:00+08:00",
      period: "AM",
      category: "applied",
      note: "note2",
    },
    {
      id: "music-0413",
      subjectZh: "音樂",
      subjectEn: "Music",
      paperZh: "1A 及 1B（註 2 檔期）",
      paperEn: "Papers 1A & 1B (Note 2 slot)",
      start: "2017-04-13T08:30:00+08:00",
      period: "AM",
      category: "arts",
      note: "note2",
    },
    {
      id: "pe-0413",
      subjectZh: "體育",
      subjectEn: "Physical Education",
      paperZh: "卷一及卷二（註 2 檔期）",
      paperEn: "Papers 1 & 2 (Note 2 slot)",
      start: "2017-04-13T08:30:00+08:00",
      period: "AM",
      category: "arts",
      note: "note2",
    },
    {
      id: "liteng-p2",
      subjectZh: "英語文學",
      subjectEn: "Literature in English",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-13T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "chihist-p1",
      subjectZh: "中國歷史",
      subjectEn: "Chinese History",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-18T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "chihist-p2",
      subjectZh: "中國歷史",
      subjectEn: "Chinese History",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-18T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "m1",
      subjectZh: "數學延伸部分",
      subjectEn: "Mathematics Extended Part",
      paperZh: "單元一 M1",
      paperEn: "Module 1",
      start: "2017-04-19T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "m2",
      subjectZh: "數學延伸部分",
      subjectEn: "Mathematics Extended Part",
      paperZh: "單元二 M2",
      paperEn: "Module 2",
      start: "2017-04-19T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "hist-p1",
      subjectZh: "歷史",
      subjectEn: "History",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-20T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "hist-p2",
      subjectZh: "歷史",
      subjectEn: "History",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-20T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "ict-p1",
      subjectZh: "資訊及通訊科技",
      subjectEn: "Information and Communication Technology",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-21T08:30:00+08:00",
      period: "AM",
      category: "applied",
    },
    {
      id: "ict-p2",
      subjectZh: "資訊及通訊科技",
      subjectEn: "Information and Communication Technology",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-21T13:30:00+08:00",
      period: "PM",
      category: "applied",
    },
    {
      id: "geog-p1",
      subjectZh: "地理",
      subjectEn: "Geography",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-22T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "geog-p2",
      subjectZh: "地理",
      subjectEn: "Geography",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-22T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "bio-p1",
      subjectZh: "生物",
      subjectEn: "Biology",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-24T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "bio-p2",
      subjectZh: "生物",
      subjectEn: "Biology",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-24T13:30:00+08:00",
      period: "PM",
      category: "science",
    },
    {
      id: "csb",
      subjectZh: "組合科學（生物）",
      subjectEn: "Combined Science (Biology)",
      paperZh: "筆試",
      paperEn: "Written paper",
      start: "2017-04-24T08:30:00+08:00",
      period: "AM",
      category: "science",
    },
    {
      id: "ers-p1",
      subjectZh: "倫理與宗教",
      subjectEn: "Ethics and Religious Studies",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-25T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "ers-p2",
      subjectZh: "倫理與宗教",
      subjectEn: "Ethics and Religious Studies",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-25T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "bafs-p1",
      subjectZh: "企業、會計與財務概論",
      subjectEn: "Business, Accounting and Financial Studies",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-26T08:30:00+08:00",
      period: "AM",
      category: "applied",
    },
    {
      id: "bafs-p2",
      subjectZh: "企業、會計與財務概論",
      subjectEn: "Business, Accounting and Financial Studies",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-26T13:30:00+08:00",
      period: "PM",
      category: "applied",
    },
    {
      id: "hmsc-p1",
      subjectZh: "健康管理與社會關懷",
      subjectEn: "Health Management and Social Care",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-27T08:30:00+08:00",
      period: "AM",
      category: "applied",
    },
    {
      id: "hmsc-p2",
      subjectZh: "健康管理與社會關懷",
      subjectEn: "Health Management and Social Care",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-27T13:30:00+08:00",
      period: "PM",
      category: "applied",
    },
    {
      id: "dat-0428-p1",
      subjectZh: "設計與應用科技",
      subjectEn: "Design and Applied Technology",
      paperZh: "卷一（註 2 交替檔期）",
      paperEn: "Paper 1 (Note 2 alternate slot)",
      start: "2017-04-28T08:30:00+08:00",
      period: "AM",
      category: "applied",
      note: "note2",
    },
    {
      id: "dat-0428-p2",
      subjectZh: "設計與應用科技",
      subjectEn: "Design and Applied Technology",
      paperZh: "卷二（註 2 交替檔期）",
      paperEn: "Paper 2 (Note 2 alternate slot)",
      start: "2017-04-28T13:30:00+08:00",
      period: "PM",
      category: "applied",
      note: "note2",
    },
    {
      id: "music-0428",
      subjectZh: "音樂",
      subjectEn: "Music",
      paperZh: "1A 及 1B（註 2 交替檔期）",
      paperEn: "Papers 1A & 1B (Note 2 alternate slot)",
      start: "2017-04-28T08:30:00+08:00",
      period: "AM",
      category: "arts",
      note: "note2",
    },
    {
      id: "pe-0428-p1",
      subjectZh: "體育",
      subjectEn: "Physical Education",
      paperZh: "卷一（註 2 交替檔期）",
      paperEn: "Paper 1 (Note 2 alternate slot)",
      start: "2017-04-28T08:30:00+08:00",
      period: "AM",
      category: "arts",
      note: "note2",
    },
    {
      id: "pe-0428-p2",
      subjectZh: "體育",
      subjectEn: "Physical Education",
      paperZh: "卷二（註 2 交替檔期）",
      paperEn: "Paper 2 (Note 2 alternate slot)",
      start: "2017-04-28T13:30:00+08:00",
      period: "PM",
      category: "arts",
      note: "note2",
    },
    {
      id: "econ-p1",
      subjectZh: "經濟",
      subjectEn: "Economics",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-04-29T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "econ-p2",
      subjectZh: "經濟",
      subjectEn: "Economics",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-04-29T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "ths-p1",
      subjectZh: "旅遊與款待",
      subjectEn: "Tourism and Hospitality Studies",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-05-02T08:30:00+08:00",
      period: "AM",
      category: "applied",
    },
    {
      id: "ths-p2",
      subjectZh: "旅遊與款待",
      subjectEn: "Tourism and Hospitality Studies",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-05-02T13:30:00+08:00",
      period: "PM",
      category: "applied",
    },
    {
      id: "chilit-p1",
      subjectZh: "中國文學",
      subjectEn: "Chinese Literature",
      paperZh: "卷一",
      paperEn: "Paper 1",
      start: "2017-05-04T08:30:00+08:00",
      period: "AM",
      category: "humanities",
    },
    {
      id: "chilit-p2",
      subjectZh: "中國文學",
      subjectEn: "Chinese Literature",
      paperZh: "卷二",
      paperEn: "Paper 2",
      start: "2017-05-04T13:30:00+08:00",
      period: "PM",
      category: "humanities",
    },
    {
      id: "reserve-0505",
      subjectZh: "後備",
      subjectEn: "Reserve",
      paperZh: "後備日（五月五日）",
      paperEn: "Reserve day (5 May)",
      start: "2017-05-05T08:30:00+08:00",
      period: "AM",
      category: "reserve",
      note: "reserve",
    },
    {
      id: "reserve-0506",
      subjectZh: "後備",
      subjectEn: "Reserve",
      paperZh: "後備日（五月六日）",
      paperEn: "Reserve day (6 May)",
      start: "2017-05-06T08:30:00+08:00",
      period: "AM",
      category: "reserve",
      note: "reserve",
    },
  ],
};
